# General commands
brew "autossh"
brew "cloc"
brew "gh"
brew "git-delta"
brew "ghq"
brew "hub"
brew "hugo"
brew "jq"
brew "mas"
brew "node"
brew "peco"
brew "pv"
brew "shellcheck"
brew "tmux"
brew "terraform"
brew "tree"
brew "watch"

# GNU
brew "coreutils"
brew "grep"
brew "gnu-sed"

# General apps
cask "1password"
cask "alt-tab"
cask "appcleaner"
cask "betterdisplay"
cask "deckset"
cask "dozer"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "iterm2"
cask "karabiner-elements"
cask "raycast"
cask "sequel-ace"
cask "slack"
cask "spotify"
cask "yubico-yubikey-manager"
cask "visual-studio-code"

# Zsh
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# Python
brew "pyenv"
brew "python"

# Ruby
brew "ruby-build"
brew "ruby"

# Go
brew "go"

# Rust
brew "rustup"

# Kubernetes
brew "kubernetes-cli"
