tap "homebrew/cask-drivers"

# General commands
brew "autossh"
brew "cloc"
brew "gh"
brew "ghq"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "mas"
brew "node"
brew "pdsh"
brew "peco"
brew "pv"
brew "shellcheck"
brew "switchaudio-osx"
brew "tmux"
brew "terraform"
brew "tree"
brew "watch"

# GNU
brew "coreutils"
brew "grep"
brew "gnu-sed"

# General apps
cask "1password"
cask "alfred"
cask "alt-tab"
cask "appcleaner"
cask "charles"
cask "clipy"
cask "dash"
cask "deckset"
cask "dozer"
cask "fliqlo"
cask "focus"
cask "google-chrome"
cask "google-drive-file-stream"
cask "grammarly-desktop"
cask "istat-menus"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "logitech-options"
cask "ngrok"
cask "nordvpn"
cask "postman"
cask "sequel-ace"
cask "skitch"
cask "slack"
cask "spotify"
cask "rectangle"
cask "yubico-yubikey-manager"
cask "visual-studio-code"

mas "MindNode 5", id: 1289197285

# Zsh
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# Python
brew "pyenv"
brew "python"

# Ruby
brew "ruby-build"
brew "ruby"

# Go
brew "go"

# Rust
brew "rustup"

# AWS
brew "awscli"
cask "session-manager-plugin"

# Kubernetes
brew "kubernetes-cli"
brew "helm"
