#!/bin/bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

defaults write com.apple.finder CreateDesktop -bool FALSE

defaults write -g NSNavPanelExpandedStateForSaveMode -boolean true

defaults write -g PMPrintingExpandedStateForPrint -boolean true

# The directory needs to be created upfront
defaults write com.apple.screencapture location ~/Pictures/Screenshots

defaults write com.apple.dock autohide -bool true

defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

defaults write com.apple.finder AppleShowAllFiles -bool true

defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$SCRIPT_PATH/iterm"

defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

defaults write -g InitialKeyRepeat -int 15

defaults write -g KeyRepeat -int 2

killall Finder

killall Dock
