#!/bin/sh

defaults write com.apple.finder CreateDesktop -bool FALSE

defaults write -g NSNavPanelExpandedStateForSaveMode -boolean true

defaults write -g PMPrintingExpandedStateForPrint -boolean true

defaults write com.apple.screencapture location ~/Pictures/ScreenCaptures

defaults write com.apple.dock use-new-list-stack -boolean true

defaults write com.apple.dock mouse-over-hilite-stack -bool true

defaults write com.apple.dock autohide -bool true

defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

defaults write com.apple.finder AppleShowAllFiles -bool true

defaults write com.apple.dt.Xcode ShowBuildOperationDuration -bool YES

killall Finder

killall Dock
