#!/bin/sh

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BREW_PATH=$SCRIPT_PATH/../brew

install_brew() {
    which -s brew
    if [[ $? != 0 ]] ; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    else
        echo "Homebrew is already installed"
    fi
}
export -f install_brew

update_brew() {
    brew update
    for brewfile in $BREW_PATH/*
    do
        brew bundle --no-lock -v --file=$brewfile
    done
}
export -f update_brew
