#!/bin/bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOT_FILES_PATH=$SCRIPT_PATH/../dotfiles
SETTINGS_PATH=$SCRIPT_PATH/../settings
SETTING_SOURCES=(
    "$SETTINGS_PATH"/vscode/settings.json
    "$SETTINGS_PATH"/calibre/profiles.json
)
SETTING_TARGETS=(
    ~/Library/Application\ Support/Code/User/settings.json
    ~/Library/Preferences/calibre/viewer/profiles.json
)

DOT_FILE_NAMES=()
for file in $DOT_FILES_PATH/.*
do
    filename=$(basename "$file")

    black_list=("." ".." ".DS_Store")
    for black_list_name in "${black_list[@]}"
    do
        if [ "$black_list_name" == "$filename" ]; then
            continue 2
        fi
    done

    DOT_FILE_NAMES+=("$filename")
done

link_dotfiles() {
    for filename in "${DOT_FILE_NAMES[@]}"
    do
        ln -s -v "$DOT_FILES_PATH/$filename" "$HOME/$filename"
    done
}

unlink_dotfiles() {
    for filename in "${DOT_FILE_NAMES[@]}"
    do
        dotfile=$HOME/$filename

        if [ -e "$dotfile" ]; then
            rm -rf -v "$dotfile"
        fi
    done
}

link_settings() {
    for i in "${!SETTING_SOURCES[@]}"
    do
        ln -s -v "${SETTING_SOURCES[$i]}" "${SETTING_TARGETS[$i]}"
    done
}

unlink_settings() {
    for target in "${SETTING_TARGETS[@]}"
    do
        if [ -e "$target" ]; then
            rm -rf -v "$target"
        fi
    done
}

update_links() {
    echo "Removing symlinks..."
    unlink_dotfiles
    unlink_settings

    echo "Creating symlinks..."
    link_dotfiles
    link_settings
}
export -f update_links
