#!/bin/sh

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOT_FILES_PATH=$SCRIPT_PATH/../dotfiles
SETTINGS_PATH=$SCRIPT_PATH/../settings
VSCODE_SETTINGS_PATH=~/Library/Application\ Support/Code/User/settings.json

DOT_FILE_NAMES=()
for file in $DOT_FILES_PATH/.*
do
    filename=`basename $file`

    black_list=("." ".." ".DS_Store")
    for black_list_name in ${black_list[@]}
    do
        if [ $black_list_name == $filename ]; then
            continue 2
        fi
    done

    DOT_FILE_NAMES+=($filename)
done

link_dotfiles() {
    for filename in ${DOT_FILE_NAMES[@]}
    do
        ln -s -v $DOT_FILES_PATH/$filename $HOME/$filename
    done
}

unlink_dotfiles() {
    for filename in ${DOT_FILE_NAMES[@]}
    do
        dotfile=$HOME/$filename

        if [ -e $dotfile ]; then
            rm -rf -v $dotfile
        fi
    done
}

link_vscode_settings() {
    ln -s -v $SETTINGS_PATH/vscode/settings.json "$VSCODE_SETTINGS_PATH"
}

unlink_vscode_settings() {
    if [ -e "$VSCODE_SETTINGS_PATH" ]; then
        rm -rf -v "$VSCODE_SETTINGS_PATH"
    fi
}

update_links() {
    echo "Removing symlinks..."
    unlink_dotfiles
    unlink_vscode_settings

    echo "Creating symlinks..."
    link_dotfiles
    link_vscode_settings
}
export -f update_links
