#!/bin/bash

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SETTINGS_PATH=$SCRIPT_PATH/../settings

update_defaults() {
    echo "Applying defaults..."
    "$SETTINGS_PATH"/defaults
}
export -f update_defaults
