#!/bin/sh

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $SCRIPT_PATH/slack_helper

slack_status "Focusing. Slack is closed. Please find me physically." :tomato:
slack_presence false
