;; Setup repositories
(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "org" "http://orgmode.org/elpa/")

;; Install packages

;; Setup
(depends-on "cask")
(depends-on "pallet")
(depends-on "init-loader")

;; Undo
(depends-on "undo-tree")
(depends-on "undohist")

;; Auto-Complete
(depends-on "auto-complete")
(depends-on "fuzzy")
(depends-on "popup")

;; Powerline
(depends-on "powerline")

;; Sticky
(depends-on "sticky")

;; Smooth-Scroll
(depends-on "smooth-scroll")

;; Helm
(depends-on "helm")
(depends-on "helm-gtags")
(depends-on "helm-descbinds")
(depends-on "helm-ag")

;; Color-Theme
(depends-on "color-theme")
(depends-on "replace-colorthemes" :git "git@github.com:emacs-jp/replace-colorthemes.git")

;; Smartparens
(depends-on "smartparens")

;; Popwin
(depends-on "popwin")

;; Anzu
(depends-on "anzu")

;; Rainbow-delimiters
(depends-on "rainbow-delimiters")

;; Flycheck
(depends-on "flycheck")

;; Multiple Cursors
(depends-on "multiple-cursors")
(depends-on "expand-region")
(depends-on "smartrep")

;; Dash At Point
(depends-on "dash-at-point")

;; Common Lisp
(depends-on "slime")
(depends-on "ac-slime")

;; Haskell
(depends-on "haskell-mode")
(depends-on "ghc")

;; Ruby
(depends-on "ruby-block")
(depends-on "ruby-electric")
;;(depends-on "inf-ruby")
;;(depends-on "rinari")
(depends-on "projectile-rails")

;; Markdown
(depends-on "markdown-mode")
;; (depends-on "realtime-markdown-viewer")
